@SpeechSynthesis.WebAPI_HostAddress = https://localhost:7021

GET {{SpeechSynthesis.WebAPI_HostAddress}}/voices/
Accept: application/json

###

POST {{SpeechSynthesis.WebAPI_HostAddress}}/speechsynthesis/
Accept: application/json

###